### ISSUE TITLE
Use fst to cache networks

### ISSUE THREAD

**Issue by mpadge** [UrbanAnalyst/m4ra#10]
- [x] Use [`fst`](https://www.fstpackage.org/) to write and read locally cached network files
- [x] Use `save/readRDS` to write associated attributes and re-attach on load.
- [ ] Use same scheme as [`dodgr/save_load_streetnet.R`](https://github.com/ATFutures/dodgr/blob/main/R/save_load_streetnet.R)

**Comment by Robinlovelace** [comment]
Or use {targets}? Impressed after recent tests!

**Comment by mpadge** [comment]
Yeah, {targets} is great, and that's probably a good idea to make this a {targets}-based workflow. What this exercise has really made me reaslise is how easier this would all be with a system like [kedro](https://github.com/kedro-org/kedro). I'd love to re-code all of {dodgr} back-end in rust, front-end in python, and it would all be so much easier.

**Comment by mpadge** [comment]
Done.
