### ISSUE TITLE
Fix fst write routines

### ISSUE THREAD

**Issue by mpadge** [UrbanAnalyst/m4ra#26]
They currently produce garbage when writing really large files (~10M rows), but seems to be because of default `compress = 50`. Setting that to `compress = 0` seems to resolve the issue.

**Comment by rafapereirabr** [comment]
Hi @mpadge . Quick question. Why did you choose to use `fst` instead of `parquet`?

**Comment by mpadge** [comment]
Hiya Rafa! Chose just because it's more lightweight, and arrow for this workflow is overkill. Everything here is internally indexed by city name; arrow would enable city to be used an index, but then you'd lose oversight of what individual files were. Does that make sense?

**Comment by rafapereirabr** [comment]
Yes, it makes perfect sense! Thanks for clarifying! I'm following your work on m4ra with great interest!

**Comment by mpadge** [comment]
Have to re-open because `fst` still produces unreliable values. The package is clearly going to have to be dumped here, because the unreliability breaks all analyses here. It seems that the row-wise ordering in different columns is randomly rearranged, so that rows are not recovered, but include random data mixed from other rows.

**Comment by mpadge** [comment]
Can't use arrow, because even with current dev version, it errors because
```
Error in rawToChar(out): long vectors not supported yet: raw.c:68
```
That's on a data frame with 6,5 million rows, 21 columns. I guess arrow still primarily envisions numerical data ... so it's back to plain old `saveRDS`. That will slow these routines down somewhat, but at least everything will once again be reliable.

**Comment by mpadge** [comment]
Confirmed that full accuracy has been regained, and load times even for the data.frame above with 6.5M rows are still well under 1 minute, which is okay
