### ISSUE TITLE
Travel modes

### ISSUE THREAD

**Issue by mpadge** [UrbanAnalyst/m4ra#4]
## Single modes

- [x] walking
- [x] cycling
- [ ] non-electric scooters
- [ ] electric scooters
- [x] motorvehicle (need to generate relative travel time estimates; see #3)

## Multiple modes in conjunction with public transport (PT)

- [x] walk -> PT -> walk
- [x] walk -> PT -> cycle
- [x] cycle -> PT -> walk
- [ ] walk -> PT -> shared scooter
- [ ] shared scooter -> PT -> walk
- [ ] non-eletric scooter -> PT -> non-electric scooter
- [ ] electric scooter -> PT -> electric scooter

Shared eletric scooters won't be analysed for now, because the areas in which they are (potentially) available are generally highly regulated, preventing the construction of any generally realistic models.

**Comment by FlxPo** [comment]
Would "car -> PT -> walk" be feasible in m4ra ?

**Comment by mpadge** [comment]
Yes, it would, but work at the moment will not consider car as an actual transport mode - car routing is only used via #3 to generate metrics of relative difference to car times. That said, the main hurdle with car -> PT is parking, in particular calculating time penalties for parking plus walking, which will also be considered for bicycle routing. So adaptation would be fairly easy once that it is place.

**Comment by mpadge** [comment]
Full multi-modal algorithm now finished via #8, and includes any combinations of default `dodgr` modes of walking and cycling. Extending to private automobile just requires time penalties for (searching for) parking, dependent on local metrics of parking availability. Extending to scooters can then be done later, but not a high priority at present.

**Comment by mpadge** [comment]
Closing this for now with current modes. Can re-open later if desired to extend to further modes.
